name: Release Extension

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  deploy-to-hf-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependecies
        run: |
          bun install
          cp node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.{wasm,mjs,jsep.wasm,jsep.mjs} public

      - name: Build and Zip Extension
        run: |
          bun wxt zip
          bun wxt zip -b firefox
        env:
          WXT_DETECTION_MODEL_REPO: ${{ secrets.WXT_DETECTION_MODEL_REPO }}
          WXT_SUPABASE_URL: ${{ secrets.WXT_SUPABASE_URL }}
          WXT_SUPABASE_PUBLIC_KEY: ${{ secrets.WXT_SUPABASE_PUBLIC_KEY }}
          WXT_LANGUAGES: ${{ secrets.WXT_LANGUAGES }}
          WXT_GEMINI_MODELS: ${{ secrets.WXT_GEMINI_MODELS }}
          WXT_DETECTION_MODELS: ${{ secrets.WXT_DETECTION_MODELS }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: .output/*.zip
          generate_release_notes: true
          draft: false
          prerelease: false